language: python
sudo: false
os:
    - linux
    ## - osx
python:
    - 2.7
    - 3.3
addons:
    apt:
        packages:
            - liblzo2-dev
before_install:
    # Use miniconda for dependencies, pip is too slow -- https://gist.github.com/zonca/9958333
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
install: 
    - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION numpy nose
    - source activate testenv
    - pip install https://github.com/cython/cython/archive/f9388e1595f8a2b5833ed4299429a291449ca03e.zip --install-option=--no-cython-compile
    - pip install python-lzo
    - python setup.py build_ext --inplace
    - python setup.py install
script: 
    - nosetests
